### ISSUE TITLE
i cant add picture !

### ISSUE THREAD

**Issue by redorc15** [ahmednooor/KrypApp#2]
Hi again ! :) i'am trying to add a picture in main form but i got this : 

Traceback (most recent call last):
  File "KrypApp.py", line 486, in <module>
    MAIN_WINDOW = MainWindow(ROOT)  
  File "KrypApp.py", line 150, in __init__
    lab = self.dd_entry_label(ROOT, image=photoImageObj).pack()
AttributeError: 'MainWindow' object has no attribute 'dd_entry_label'

----------------------------------------------------------------------------------------------------------------
my code is  :  
photoImageObj = PhotoImage(file="dd.png")   
lab = self.dd_entry_label(ROOT, image=photoImageObj).pack()
-----------------------------------------------------------------------------------------------------------------
i'am trying to modify that code to work on KrypApp : 

root = tk.Tk()

photoImageObj = tk.PhotoImage(file="code_girl01.png")
lab = tk.Label(root, image=photoImageObj).pack()

root.mainloop()

**Comment by ahmednooor** [comment]
You will need to put the code in the `__init__` of `MainWindow` like this,
```python
self.logo_icon = tk.PhotoImage(file="./assets/icon.png")
self.icon_label = tk.Label(root, image=self.logo_icon)
self.icon_label.grid(row=0, column=5)
```
also, you can't use `.pack()` in the grid layout. you will need to use `.grid()` like above.

for further reading, [https://effbot.org/tkinterbook/](https://effbot.org/tkinterbook/) is a good resource. Thank you.

Closing this now.
