### ISSUE TITLE
Progressbar with encrypt/decrypt functions !

### ISSUE THREAD

**Issue by redorc15** [ahmednooor/KrypApp#3]
Hi again :)..... i want to make a progressbar because when i encrypt a large files it looks like its frozen ( it seem a good idea but i'am stuck xDD )

i want to make it related with the encryption/decryption functions but only what i found on youtube etc between two values for exemple : ( 1 to 100 )
any idea ! i'll be thankful !

Waiting for your response thanks ! :)

**Comment by ahmednooor** [comment]
Hello I am afraid I won't be able to help much. For progress bar, you will need to move the encryption/decryption process to another thread and progress bar to another thread. Even then you might not be able to show the percentage as the percentage can only be given to you from inside the encryption/decryption process. The most you can do is to show a text such as "Encrypting/Decrypting" during the process.

Good luck.
Closing this now.
