### ISSUE TITLE
Select AES type with Combobox !

### ISSUE THREAD

**Issue by redorc15** [ahmednooor/KrypApp#4]
Hi ! i Too much questions ! ( sorry ) but i really like your project ( i've never found such a great implementation of pycryptodome like this ! )  i'am trying to do my best to make it better :) HOPE YOU UNDERSTAND ME ! xD
----------------------------------------------------------------------
i've just creat combobox to select Aes type !

self.comboExample = ttk.Combobox(root,
                                        values=[
                                                "AES-128", 
                                                "AES-192",
                                                "AES-256"]
        )
        self.comboExample.grid(
           padx=(15, 3),
           pady=8,
           ipadx=0,
           ipady=1,
           row=0,
           column=4,
           columnspan=4
        )

        self.comboExample.set("Select AES Type !"
        )
i've creat two other classes : 
-class EncryptionTool2 ( for aes 192 )
-class EncryptionTool3 ( for aes 256 )

-----------------------------------------------------------
i want make : 
if combobox = Aes-256      or       if combobox = Aes-192      or      if combobox = Aes-128

it will change here : 
def encrypt_callback(self):
        try:
      self._cipher = EncryptionTool( ------- ( this will change to EncryptionTool2 or EncryptionTool3
                self._file_url.get(),
                self._secret_key.get(),
                self._salt.get()
            )
            self._cipher.encrypt()
            self._cipher = None
            self._status.set("File encrypted!")
        except Exception as e:
            # print(e)
            self._status.set(e)

Waiting for your response ! THANK YOU !

**Comment by ahmednooor** [comment]
Hello I am quite busy and won't be able to help much. What you can do is,
1) ask the user what aes type is required.
2) add a new param in EncryptionTool class, which will be based on the aes type. then only take the bytes from the input key hash like 16, 24 or 32 bytes according to aes type like 128 bits (16 bytes) 192 bits (24 bytes) and 256 bits (32 bytes).

Good luck.
Closing this now.
