### ISSUE TITLE
Program freeze + system freeze !!!

### ISSUE THREAD

**Issue by redorc15** [ahmednooor/KrypApp#5]
Hi again ! there is another issue ! when i encrypt a large file ( ex: 1gb ) the program freez and after few second all system gui interface freeze ( i try it on windows 10/ Ubuntu 18.04 / parrot os 3.7 and got same thing )

i've heared about multiprocessing but i dont know how to start !

may that help you : 

https://docs.python.org/3.5/library/multiprocessing.html#module-multiprocessing

**Comment by redorc15** [comment]
+ Remarque : 
when i changed the priority to very high in system monitor ( system will not freez ! ) but the prorame
consums up to 1.8 Gb of ram !

**Comment by ahmednooor** [comment]
I think that is because the whole file gets loaded into memory which stalls the system. One way might be to do it in chunks. Feel free to experiment with it as I don't get time for it.
I will be closing this now. Thank you.
