### ISSUE TITLE
Copyright Content...

### ISSUE THREAD

**Issue by ghost** [ahmednooor/KrypApp#6]
Hiii ahmednooor,
This is Dhruv, I've seen your code and it's amazing. I am still working by taking this as a reference. Meanwhile, I was surfing on other Projects and I came across the link:-
https://github.com/rgdeekshith/File-Encrypt-App-using-Python
which has all the content of yours and published by his/her name without credits. So I suggest you to report this account and claim your Copyrightand solve further issues.

**Comment by ahmednooor** [comment]
Hello, thank you for letting me know.
This is an open source project and it is in public domain, so people can do whatever they want with it. I too took the encryption class from somewhere else and modified it. Credit is not necessary.
I hope this helps. Feel free to experiment with it. Take care and good luck. Bye.
