### ISSUE TITLE
Change the app name and icon

### ISSUE THREAD

**Issue by soshinde** [ahmednooor/KrypApp#7]
Hi ahmednoor,
I am Sonali,
I tried your application it is very nice. 
Actually, I use your app for educational purpose so please help me in one thing. 
I want to change the app icon and name, I have lost try to change it but no luck so please help me on that.

Thank you.

**Comment by ahmednooor** [comment]
Hello @soshinde 

To change the icons, you can replace `.png` and `.ico` with your icons in the following directory.
- https://github.com/ahmednooor/KrypApp/tree/master/assets

To change name, you can edit it in the following files.
- https://github.com/ahmednooor/KrypApp/blob/master/KrypApp.py#L194
- https://github.com/ahmednooor/KrypApp/blob/master/setup.py#L18
